/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pacifickode;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author chath
 */
public class BillingWindow extends javax.swing.JFrame {
    
//    Connection from DB Class-----------------------------------------
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    DefaultTableModel df;
    
//    CONSTRUCTOR=================================================================
    public BillingWindow() {
        initComponents();
        con = DbConnection.dbConnection();
        view_tableData();
        view_subtotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        discountfld = new javax.swing.JTextField();
        unitpricefld = new javax.swing.JTextField();
        itemnamefld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalfld = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addtobillbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deletefrmbillbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoicetb = new javax.swing.JTable();
        paybtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        printbillbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        itemcode = new javax.swing.JTextField();
        qtity = new javax.swing.JTextField();
        subttl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Fast Hand", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("PacificKode");

        discountfld.setBackground(new java.awt.Color(204, 204, 204));
        discountfld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountfldKeyReleased(evt);
            }
        });

        unitpricefld.setBackground(new java.awt.Color(204, 204, 204));
        unitpricefld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpricefldActionPerformed(evt);
            }
        });

        itemnamefld.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Item Name");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Unit Price");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Quantity");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Discount");

        totalfld.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Total");

        addtobillbtn.setBackground(new java.awt.Color(0, 51, 153));
        addtobillbtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        addtobillbtn.setForeground(new java.awt.Color(255, 255, 255));
        addtobillbtn.setText("ADD TO BILL");
        addtobillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtobillbtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Created By A M C U Adhikary ( All Rights Reserved)");

        jLabel2.setFont(new java.awt.Font("Doppio One", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("BILLING AREA");

        deletefrmbillbtn.setBackground(new java.awt.Color(0, 51, 153));
        deletefrmbillbtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        deletefrmbillbtn.setForeground(new java.awt.Color(255, 0, 0));
        deletefrmbillbtn.setText("DELETE FROM BILL");
        deletefrmbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletefrmbillbtnActionPerformed(evt);
            }
        });

        invoicetb.setBackground(new java.awt.Color(255, 255, 255));
        invoicetb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Unit Price", "Quantity", "Discount", "Total"
            }
        ));
        invoicetb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoicetbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(invoicetb);

        paybtn.setBackground(new java.awt.Color(51, 204, 0));
        paybtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        paybtn.setForeground(new java.awt.Color(255, 255, 255));
        paybtn.setText("CASH");
        paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("TOTAL");

        printbillbtn.setBackground(new java.awt.Color(51, 204, 0));
        printbillbtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        printbillbtn.setForeground(new java.awt.Color(255, 255, 255));
        printbillbtn.setText("CREDIT CARD");
        printbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbillbtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Item Code");

        itemcode.setBackground(new java.awt.Color(204, 204, 204));
        itemcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemcodeKeyPressed(evt);
            }
        });

        qtity.setBackground(new java.awt.Color(204, 204, 204));
        qtity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtityActionPerformed(evt);
            }
        });
        qtity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtityKeyReleased(evt);
            }
        });

        subttl.setBackground(new java.awt.Color(255, 255, 255));
        subttl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        subttl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                subttlMouseReleased(evt);
            }
        });
        subttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subttlActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("SELECT PAYMENT METHOD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deletefrmbillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addtobillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalfld, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemnamefld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unitpricefld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(discountfld, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(qtity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemcode, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(paybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(116, 116, 116)
                                        .addComponent(printbillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(169, 169, 169)))
                                .addComponent(subttl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(235, 235, 235))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(itemcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(itemnamefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(unitpricefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(qtity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(discountfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(addtobillbtn)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletefrmbillbtn)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printbillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(subttl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)))
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unitpricefldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpricefldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpricefldActionPerformed

     // DELETE FROM BILL  GOES HERE=====================================================================
    private void deletefrmbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletefrmbillbtnActionPerformed
            int idk = Integer.parseInt(itemcode.getText());
            String sql = "DELETE FROM billing WHERE id='"+idk+ "'";
            try{
               ps = con.prepareStatement(sql);
               ps.execute();
               JOptionPane.showMessageDialog(null, "Record Deleted Successfully");
               view_tableData();
                itemcode.setText("");
                itemnamefld.setText("");
                unitpricefld.setText("");
                qtity.setText("");
                discountfld.setText("");
                totalfld.setText("");
               
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            
            }
            
    }//GEN-LAST:event_deletefrmbillbtnActionPerformed
       
    // ADD TO BILL BTN GOES HERE========================================================================
    private void addtobillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtobillbtnActionPerformed
        String id = itemcode.getText();
        String itemname = itemnamefld.getText();
        String unit_price = unitpricefld.getText() ;
        String quantity = qtity.getText();
        String discount =discountfld.getText() ;
        String total = totalfld.getText();
        if(itemnamefld.getText().isBlank()&& itemnamefld.getText().isBlank() && unitpricefld.getText().isBlank() && qtity.getText().isBlank() && discountfld.getText().isBlank() && totalfld.getText().isBlank() ){
            JOptionPane.showMessageDialog(null, "All the fields are Required");
        }else{
            String sql = "INSERT INTO billing (id,itemname,unit_price,quantity,discount,total )  VALUES (?,?,?,?,?,?)";
            try{
                ps = con.prepareStatement(sql);
                int i = Integer.parseInt(id);
                ps.setInt(1,i);
                ps.setString(2, itemname);
                ps.setString(3, unit_price);
                ps.setString(4, quantity);
                ps.setString(5, discount);
                ps.setString(6, total);
                ps.execute();
                JOptionPane.showMessageDialog(this, "ITEM ADDED..!");
                
                itemcode.setText("");
                itemnamefld.setText("");
                unitpricefld.setText("");
                qtity.setText("");
                discountfld.setText("");
                totalfld.setText("");
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            };
        }
    }//GEN-LAST:event_addtobillbtnActionPerformed

        //VIEW BILLING TABLE GOES HERE ===================================================
        public void view_tableData() {
            try {
               String sql = "SELECT * FROM billing";
               ps = con.prepareStatement(sql);
               rs = ps.executeQuery();
               invoicetb.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {
                Logger.getLogger(BillingWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    private void itemcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemcodeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemcodeKeyPressed

    private void qtityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtityActionPerformed

    }//GEN-LAST:event_qtityActionPerformed

    // SUBTOTAL CALCULATION===================================================================
    public void view_subtotal() {
       String sql = "SELECT SUM(total) as sum_total FROM billing";
        try {
             ps = con.prepareStatement(sql);
             rs = ps.executeQuery();  
             String sum = rs.getString("sum_total");
                subttl.setText(sum);
             
        } catch (SQLException ex) {
            Logger.getLogger(BillingWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void subttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subttlActionPerformed
  
    }//GEN-LAST:event_subttlActionPerformed

//    CREDITCARD PAYMENT BTN GOES HERE ==================================================================
    private void printbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbillbtnActionPerformed
       CardPayment inv = new CardPayment();
       inv.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_printbillbtnActionPerformed

//    INVOICE MOUSE CLICKED EVENTS GOES HERE ===============================================================
    private void invoicetbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoicetbMouseClicked
        int row = invoicetb.getSelectedRow();
        String idn = invoicetb.getModel().getValueAt(row, 0).toString();
        String sql = "SELECT * FROM billing WHERE id='" +idn+ "' ";
        try{
            ps =con.prepareStatement(sql);
            rs = ps.executeQuery();
                if(rs.next()){
                String itemname = rs.getString(2);
                String unit_price = rs.getString(3);
                String quantity = rs.getString(4);
                String discount =rs.getString(5);
                String total = rs.getString(6);
                
                itemcode.setText(idn);
                itemnamefld.setText(itemname);
                unitpricefld.setText(unit_price);
                qtity.setText(quantity);
                discountfld.setText( discount);
                totalfld.setText(total);
                view_tableData();
                
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_invoicetbMouseClicked

    private void qtityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtityKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_qtityKeyReleased
     
//    Discount and Quntity aginst Unit Price Calculation Goes Here ======================================================================
    private void discountfldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountfldKeyReleased

        Double price = Double.parseDouble(unitpricefld.getText()) ;
        Integer items = Integer.parseInt(qtity.getText());
        Double dicounts = Double.parseDouble(discountfld.getText());
        Double total2 = (price*items) -dicounts; 
        totalfld.setText(total2.toString());
    }//GEN-LAST:event_discountfldKeyReleased

//    CASH PAYMENT WINDOW REDIRECTION ==================================================================================
    private void paybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybtnActionPerformed
       CashPayment inv = new CashPayment();
       inv.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_paybtnActionPerformed

    private void subttlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subttlMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_subttlMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtobillbtn;
    private javax.swing.JButton deletefrmbillbtn;
    private javax.swing.JTextField discountfld;
    private javax.swing.JTable invoicetb;
    private javax.swing.JTextField itemcode;
    private javax.swing.JTextField itemnamefld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton paybtn;
    private javax.swing.JButton printbillbtn;
    private javax.swing.JTextField qtity;
    private javax.swing.JTextField subttl;
    private javax.swing.JTextField totalfld;
    private javax.swing.JTextField unitpricefld;
    // End of variables declaration//GEN-END:variables
}
